insert into StateAgency (name, state) values ("Texas Guaranteed Student Loan", "TX");
insert into StateAgency (name, state) values ("Texas Mutual Insurance Company", "TX");
insert into StateAgency (name, state) values ("Texas State Affordable Housing Corporation", "TX");
insert into StateAgency (name, state) values ("Correctional Managed Health Care Committee", "TX");
insert into StateAgency (name, state) values ("Texas A&M Research Foundation", "TX");
insert into StateAgency (name, state) values ("Texas Council on Alzheimer's Disease and Related Disorders", "TX");
insert into StateAgency (name, state) values ("Senate", "TX");
insert into StateAgency (name, state) values ("House of Representatives", "TX");
insert into StateAgency (name, state) values ("Texas Legislative Council", "TX");
insert into StateAgency (name, state) values ("Legislative Budget Board", "TX");
insert into StateAgency (name, state) values ("Legislative Reference Library", "TX");
insert into StateAgency (name, state) values ("Commission on Uniform State Laws (Administered by 103)", "TX");
insert into StateAgency (name, state) values ("Sunset Advisory Commission", "TX");
insert into StateAgency (name, state) values ("Supreme Court", "TX");
insert into StateAgency (name, state) values ("State Bar of Texas", "TX");
insert into StateAgency (name, state) values ("Board of Law Examiners", "TX");
insert into StateAgency (name, state) values ("Court Reporter Certification Board (Administered by 212)", "TX");
insert into StateAgency (name, state) values ("Judicial Branch Certification Commission", "TX");
insert into StateAgency (name, state) values ("Court of Criminal Appeals", "TX");
insert into StateAgency (name, state) values ("Office of Court Administration", "TX");
insert into StateAgency (name, state) values ("Office of State Prosecuting Attorney", "TX");
insert into StateAgency (name, state) values ("Office of Capital and Forensic Writs", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – First Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Second Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Third Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Fourth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Fifth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Sixth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Seventh Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Eighth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Ninth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Tenth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Eleventh Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Twelfth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Thirteenth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("Court of Appeals – Fourteenth Court of Appeals District", "TX");
insert into StateAgency (name, state) values ("District Courts – Comptroller's Judiciary Section", "TX");
insert into StateAgency (name, state) values ("State Commission on Judicial Conduct", "TX");
insert into StateAgency (name, state) values ("State Law Library", "TX");
insert into StateAgency (name, state) values ("Governor – Fiscal", "TX");
insert into StateAgency (name, state) values ("Governor – Executive", "TX");
insert into StateAgency (name, state) values ("Attorney General", "TX");
insert into StateAgency (name, state) values ("Texas Facilities Commission", "TX");
insert into StateAgency (name, state) values ("Comptroller of Public Accounts", "TX");
insert into StateAgency (name, state) values ("General Land Office", "TX");
insert into StateAgency (name, state) values ("Texas State Library and Archives Commission", "TX");
insert into StateAgency (name, state) values ("Secretary of State", "TX");
insert into StateAgency (name, state) values ("State Auditor", "TX");
insert into StateAgency (name, state) values ("Comptroller – Treasury Fiscal", "TX");
insert into StateAgency (name, state) values ("State Securities Board", "TX");
insert into StateAgency (name, state) values ("Department of Information Resources", "TX");
insert into StateAgency (name, state) values ("Comptroller – Prepaid Higher Education Tuition Board", "TX");
insert into StateAgency (name, state) values ("Texas Workforce Commission", "TX");
insert into StateAgency (name, state) values ("Teacher Retirement System of Texas", "TX");
insert into StateAgency (name, state) values ("Firefighter's Pension Commissioner (abolished)", "TX");
insert into StateAgency (name, state) values ("Texas Emergency Services Retirement System", "TX");
insert into StateAgency (name, state) values ("Employees Retirement System of Texas", "TX");
insert into StateAgency (name, state) values ("Veterans Land Board (Administered by 305)", "TX");
insert into StateAgency (name, state) values ("Texas Real Estate Commission", "TX");
insert into StateAgency (name, state) values ("Texas Department of Housing and Community Affairs", "TX");
insert into StateAgency (name, state) values ("Office of State–Federal Relations", "TX");
insert into StateAgency (name, state) values ("State Pension Review Board", "TX");
insert into StateAgency (name, state) values ("Inaugural Committee (Administered by 307)", "TX");
insert into StateAgency (name, state) values ("Texas Public Finance Authority", "TX");
insert into StateAgency (name, state) values ("Bond Review Board", "TX");
insert into StateAgency (name, state) values ("Texas Ethics Commission", "TX");
insert into StateAgency (name, state) values ("Texas Department of Rural Affairs (Administered by 551)", "TX");
insert into StateAgency (name, state) values ("Office of Public Insurance Counsel", "TX");
insert into StateAgency (name, state) values ("State Office of Administrative Hearings", "TX");
insert into StateAgency (name, state) values ("Office for the Prevention of Developmental Disabilities (Administered by 529)", "TX");
insert into StateAgency (name, state) values ("Texas Lottery Commission", "TX");
insert into StateAgency (name, state) values ("Texas Workforce Investment Council (Administered by 301)", "TX");
insert into StateAgency (name, state) values ("Health Professions Council", "TX");
insert into StateAgency (name, state) values ("Alternative Fuels Council (Administered by 907)", "TX");
insert into StateAgency (name, state) values ("State Council on Competitive Government (Administered by 304)", "TX");
insert into StateAgency (name, state) values ("Automobile Burglary and Theft Prevention Authority (Administered by 608)", "TX");
insert into StateAgency (name, state) values ("Texas Military Department", "TX");
insert into StateAgency (name, state) values ("Texas Veterans Commission", "TX");
insert into StateAgency (name, state) values ("Department of Public Safety", "TX");
insert into StateAgency (name, state) values ("Texas Commission on Law Enforcement", "TX");
insert into StateAgency (name, state) values ("Commission on Jail Standards", "TX");
insert into StateAgency (name, state) values ("Texas Commission on Fire Protection", "TX");
insert into StateAgency (name, state) values ("Office of Injured Employee Counsel (Administered by 454)", "TX");
insert into StateAgency (name, state) values ("Department of Savings and Mortgage Lending", "TX");
insert into StateAgency (name, state) values ("Texas Department of Banking", "TX");
insert into StateAgency (name, state) values ("Texas Department of Licensing and Regulation", "TX");
insert into StateAgency (name, state) values ("Texas Department of Insurance", "TX");
insert into StateAgency (name, state) values ("Railroad Commission of Texas", "TX");
insert into StateAgency (name, state) values ("Board of Plumbing Examiners", "TX");
insert into StateAgency (name, state) values ("Texas State Board of Public Accountancy", "TX");
insert into StateAgency (name, state) values ("Texas Alcoholic Beverage Commission", "TX");
insert into StateAgency (name, state) values ("Texas Board of Architectural Examiners", "TX");
insert into StateAgency (name, state) values ("Texas Board of Professional Engineers", "TX");
insert into StateAgency (name, state) values ("Texas Board of Professional Land Surveying", "TX");
insert into StateAgency (name, state) values ("Office of Consumer Credit Commissioner", "TX");
insert into StateAgency (name, state) values ("Credit Union Department", "TX");
insert into StateAgency (name, state) values ("Motor Vehicle Board (Administered by 608)", "TX");
insert into StateAgency (name, state) values ("Public Utility Commission of Texas", "TX");
insert into StateAgency (name, state) values ("Office of Public Utility Counsel", "TX");
insert into StateAgency (name, state) values ("Texas Racing Commission", "TX");
insert into StateAgency (name, state) values ("Commission on State Emergency Communications", "TX");
insert into StateAgency (name, state) values ("State Office of Risk Management", "TX");
insert into StateAgency (name, state) values ("Texas Board of Professional Geoscientists", "TX");
insert into StateAgency (name, state) values ("Texas Medical Board", "TX");
insert into StateAgency (name, state) values ("State Board of Dental Examiners", "TX");
insert into StateAgency (name, state) values ("University of Texas M. D. Anderson Cancer Center", "TX");
insert into StateAgency (name, state) values ("Texas Board of Nursing", "TX");
insert into StateAgency (name, state) values ("Texas Board of Chiropractic Examiners", "TX");
insert into StateAgency (name, state) values ("State Board of Podiatric Medical Examiners", "TX");
insert into StateAgency (name, state) values ("Texas Funeral Service Commission", "TX");
insert into StateAgency (name, state) values ("Texas Optometry Board", "TX");
insert into StateAgency (name, state) values ("Texas State Board of Pharmacy", "TX");
insert into StateAgency (name, state) values ("Board of Examiners of Psychologists", "TX");
insert into StateAgency (name, state) values ("Board of Physical Therapy Examiners (Administered by 533)", "TX");
insert into StateAgency (name, state) values ("Texas Cancer Council (Dissolved)", "TX");
insert into StateAgency (name, state) values ("State Anatomical Board", "TX");
insert into StateAgency (name, state) values ("Health and Human Services Commission", "TX");
insert into StateAgency (name, state) values ("Department of Family and Protective Services", "TX");
insert into StateAgency (name, state) values ("Executive Council of Physical and Occupational Therapy Examiners", "TX");
insert into StateAgency (name, state) values ("Board of Occupational Therapy Examiners (Administered by 533)", "TX");
insert into StateAgency (name, state) values ("Texas Low–Level Radioactive Waste Disposal Compact Commission", "TX");
insert into StateAgency (name, state) values ("Department of State Health Services", "TX");
insert into StateAgency (name, state) values ("Department of Assistive and Rehabilitative Services", "TX");
insert into StateAgency (name, state) values ("Department of Aging and Disability Services", "TX");
insert into StateAgency (name, state) values ("Cancer Prevention and Research Institute of Texas", "TX");
insert into StateAgency (name, state) values ("Texas Civil Commitment Office", "TX");
insert into StateAgency (name, state) values ("Department of Agriculture", "TX");
insert into StateAgency (name, state) values ("Texas Animal Health Commission", "TX");
insert into StateAgency (name, state) values ("Texas A&M AgriLife Extension Service", "TX");
insert into StateAgency (name, state) values ("Texas A&M AgriLife Research", "TX");
insert into StateAgency (name, state) values ("Texas A&M Veterinary Medical Diagnostic Laboratory", "TX");
insert into StateAgency (name, state) values ("Texas A&M Forest Service", "TX");
insert into StateAgency (name, state) values ("State Board of Veterinary Medical Examiners", "TX");
insert into StateAgency (name, state) values ("Rio Grande Compact Commission", "TX");
insert into StateAgency (name, state) values ("Texas Water Development Board", "TX");
insert into StateAgency (name, state) values ("Texas Commission on Environmental Quality", "TX");
insert into StateAgency (name, state) values ("Sabine River Compact Administration", "TX");
insert into StateAgency (name, state) values ("Soil and Water Conservation Board", "TX");
insert into StateAgency (name, state) values ("Red River Compact Commission", "TX");
insert into StateAgency (name, state) values ("Canadian River Commission", "TX");
insert into StateAgency (name, state) values ("Pecos River Compact Commission", "TX");
insert into StateAgency (name, state) values ("Texas Department of Transportation", "TX");
insert into StateAgency (name, state) values ("Turnpike Authority – Local", "TX");
insert into StateAgency (name, state) values ("Texas Department of Motor Vehicles", "TX");
insert into StateAgency (name, state) values ("Office of Independent Ombudsman", "TX");
insert into StateAgency (name, state) values ("Texas Juvenile Justice Department", "TX");
insert into StateAgency (name, state) values ("Texas Correctional Office on Offenders with Medical or Mental Impairments (Administered by 696)", "TX");
insert into StateAgency (name, state) values ("Texas Juvenile Probation Commission (abolished) (Administered by 644)", "TX");
insert into StateAgency (name, state) values ("Texas Center for Infectious Disease (Administered by 537)", "TX");
insert into StateAgency (name, state) values ("Rio Grande State Center (Administered by 537)", "TX");
insert into StateAgency (name, state) values ("Texas Youth Commission (abolished) (Administered by 644)", "TX");
insert into StateAgency (name, state) values ("Texas Department of Criminal Justice", "TX");
insert into StateAgency (name, state) values ("Texas Education Agency", "TX");
insert into StateAgency (name, state) values ("Public Community/Junior Colleges (Administered by 781)", "TX");
insert into StateAgency (name, state) values ("State Board for Educator Certification (Administered by 701)", "TX");
insert into StateAgency (name, state) values ("Texas A&M University System –– Office of Technology Commercialization", "TX");
insert into StateAgency (name, state) values ("Texas A&M University System – Office of Sponsored Research Services", "TX");
insert into StateAgency (name, state) values ("Texas A&M University System Health Science Center", "TX");
insert into StateAgency (name, state) values ("Texas A&M University System", "TX");
insert into StateAgency (name, state) values ("Texas A&M University (Main University)", "TX");
insert into StateAgency (name, state) values ("Texas A&M Engineering Experiment Station", "TX");
insert into StateAgency (name, state) values ("Tarleton State University", "TX");
insert into StateAgency (name, state) values ("University of Texas at Arlington", "TX");
insert into StateAgency (name, state) values ("Prairie View A&M University", "TX");
insert into StateAgency (name, state) values ("Texas A&M Engineering Extension Service", "TX");
insert into StateAgency (name, state) values ("Texas Southern University", "TX");
insert into StateAgency (name, state) values ("Texas A&M University at Galveston", "TX");
insert into StateAgency (name, state) values ("Texas State Technical College System", "TX");
insert into StateAgency (name, state) values ("University of Texas System", "TX");
insert into StateAgency (name, state) values ("University of Texas at Austin", "TX");
insert into StateAgency (name, state) values ("University of Texas Medical Branch at Galveston", "TX");
insert into StateAgency (name, state) values ("University of Texas at El Paso", "TX");
insert into StateAgency (name, state) values ("Texas A&M Transportation Institute", "TX");
insert into StateAgency (name, state) values ("University of Texas Southwestern Medical Center", "TX");
insert into StateAgency (name, state) values ("University of Houston", "TX");
insert into StateAgency (name, state) values ("Texas Woman's University", "TX");
insert into StateAgency (name, state) values ("Texas A&M University – Kingsville", "TX");
insert into StateAgency (name, state) values ("Texas Tech University", "TX");
insert into StateAgency (name, state) values ("Lamar University", "TX");
insert into StateAgency (name, state) values ("Midwestern State University", "TX");
insert into StateAgency (name, state) values ("University of Texas – Pan American", "TX");
insert into StateAgency (name, state) values ("Angelo State University", "TX");
insert into StateAgency (name, state) values ("University of Texas at Dallas", "TX");
insert into StateAgency (name, state) values ("Texas Tech University Health Sciences Center", "TX");
insert into StateAgency (name, state) values ("University of Texas of the Permian Basin", "TX");
insert into StateAgency (name, state) values ("University of Texas at San Antonio", "TX");
insert into StateAgency (name, state) values ("University of Texas Health Science Center at Houston", "TX");
insert into StateAgency (name, state) values ("University of Texas Health Science Center at San Antonio", "TX");
insert into StateAgency (name, state) values ("University of Texas at Rio Grande Valley", "TX");
insert into StateAgency (name, state) values ("University of Texas at Brownsville", "TX");
insert into StateAgency (name, state) values ("Texas A&M University at San Antonio", "TX");
insert into StateAgency (name, state) values ("University of Texas at Tyler", "TX");
insert into StateAgency (name, state) values ("Texas A&M University – Commerce", "TX");
insert into StateAgency (name, state) values ("University of North Texas", "TX");
insert into StateAgency (name, state) values ("Sam Houston State University", "TX");
insert into StateAgency (name, state) values ("Texas State University", "TX");
insert into StateAgency (name, state) values ("Stephen F. Austin State University", "TX");
insert into StateAgency (name, state) values ("Sul Ross State University", "TX");
insert into StateAgency (name, state) values ("West Texas A&M University", "TX");
insert into StateAgency (name, state) values ("Texas State University System", "TX");
insert into StateAgency (name, state) values ("University of Houston – Clear Lake", "TX");
insert into StateAgency (name, state) values ("Texas A&M University – Corpus Christi", "TX");
insert into StateAgency (name, state) values ("Texas A&M International University", "TX");
insert into StateAgency (name, state) values ("University of North Texas Health Science Center at Fort Worth", "TX");
insert into StateAgency (name, state) values ("Texas A&M University – Texarkana", "TX");
insert into StateAgency (name, state) values ("University of Houston – Victoria", "TX");
insert into StateAgency (name, state) values ("State Medical Education Board (abolished)", "TX");
insert into StateAgency (name, state) values ("Texas Tech University System", "TX");
insert into StateAgency (name, state) values ("University of North Texas System", "TX");
insert into StateAgency (name, state) values ("Texas A&M University – Central Texas", "TX");
insert into StateAgency (name, state) values ("Texas School for the Blind and Visually Impaired", "TX");
insert into StateAgency (name, state) values ("Texas School for the Deaf", "TX");
insert into StateAgency (name, state) values ("University of North Texas at Dallas", "TX");
insert into StateAgency (name, state) values ("Texas Tech University Health Sciences Center – El Paso", "TX");
insert into StateAgency (name, state) values ("Texas Higher Education Coordinating Board", "TX");
insert into StateAgency (name, state) values ("University of Houston System", "TX");
insert into StateAgency (name, state) values ("University of Houston – Downtown", "TX");
insert into StateAgency (name, state) values ("University of Texas Health Science Center at Tyler", "TX");
insert into StateAgency (name, state) values ("Lamar State College – Orange", "TX");
insert into StateAgency (name, state) values ("Lamar State College – Port Arthur", "TX");
insert into StateAgency (name, state) values ("Lamar Institute of Technology", "TX");
insert into StateAgency (name, state) values ("CAFR Reporting (Texas Tech University System)", "TX");
insert into StateAgency (name, state) values ("CAFR Reporting (University of North Texas System)", "TX");
insert into StateAgency (name, state) values ("CAFR Reporting (Texas State University System)", "TX");
insert into StateAgency (name, state) values ("CAFR Reporting (University of Houston System)", "TX");
insert into StateAgency (name, state) values ("CAFR Reporting (Texas A&M University System)", "TX");
insert into StateAgency (name, state) values ("CAFR Reporting (University of Texas System)", "TX");
insert into StateAgency (name, state) values ("Parks and Wildlife Department", "TX");
insert into StateAgency (name, state) values ("Texas Historical Commission", "TX");
insert into StateAgency (name, state) values ("State Preservation Board", "TX");
insert into StateAgency (name, state) values ("The French Embassy", "TX");
insert into StateAgency (name, state) values ("The Alamo", "TX");
insert into StateAgency (name, state) values ("Texas Commission on the Arts", "TX");
insert into StateAgency (name, state) values ("Texas Emancipation Juneteenth Cultural and Historical Commission", "TX");
insert into StateAgency (name, state) values ("Comptroller – State Fiscal", "TX");
insert into StateAgency (name, state) values ("Comptroller – Funds Management", "TX");
insert into StateAgency (name, state) values ("Comptroller – State Energy Conservation Office", "TX");
insert into StateAgency (name, state) values ("Texas Treasury Safekeeping Trust Company", "TX");
