insert into StateAgency (name, state) values ("Agency for Health Care Administration", "FL");
insert into StateAgency (name, state) values ("Agency for Persons With Disabilities", "FL");
insert into StateAgency (name, state) values ("Agency for Workforce Innovation", "FL");
insert into StateAgency (name, state) values ("Attorney General", "FL");
insert into StateAgency (name, state) values ("Auditor General", "FL");
insert into StateAgency (name, state) values ("Department of Agriculture and Consumer Services", "FL");
insert into StateAgency (name, state) values ("Department of Business and Professional Regulation", "FL");
insert into StateAgency (name, state) values ("Department of Children and Families", "FL");
insert into StateAgency (name, state) values ("Department of Citrus", "FL");
insert into StateAgency (name, state) values ("Department of Community Affairs (See Economic Opportunity)", "FL");
insert into StateAgency (name, state) values ("Department of Corrections", "FL");
insert into StateAgency (name, state) values ("Department of Economic Opportunity", "FL");
insert into StateAgency (name, state) values ("Department of Education", "FL");
insert into StateAgency (name, state) values ("Department of Elder Affairs", "FL");
insert into StateAgency (name, state) values ("Department of Environmental Protection", "FL");
insert into StateAgency (name, state) values ("Department of Financial Services", "FL");
insert into StateAgency (name, state) values ("Department of Health", "FL");
insert into StateAgency (name, state) values ("Department of Highway Safety and Motor Vehicles", "FL");
insert into StateAgency (name, state) values ("Department of Juvenile Justice", "FL");
insert into StateAgency (name, state) values ("Department of Law Enforcement", "FL");
insert into StateAgency (name, state) values ("Department of Legal Affairs", "FL");
insert into StateAgency (name, state) values ("Department of Lottery", "FL");
insert into StateAgency (name, state) values ("Department of Management Services", "FL");
insert into StateAgency (name, state) values ("Department of Military Affairs", "FL");
insert into StateAgency (name, state) values ("Department of Revenue", "FL");
insert into StateAgency (name, state) values ("Department of State", "FL");
insert into StateAgency (name, state) values ("Department of Transportation", "FL");
insert into StateAgency (name, state) values ("Department of Veterans’ Affairs", "FL");
insert into StateAgency (name, state) values ("Division of Administrative Hearings", "FL");
insert into StateAgency (name, state) values ("Division of Emergency Management", "FL");
insert into StateAgency (name, state) values ("Division of Retirement", "FL");
insert into StateAgency (name, state) values ("Division of State Group Insurance", "FL");
insert into StateAgency (name, state) values ("Enterprise Florida", "FL");
insert into StateAgency (name, state) values ("Executive Office of the Governor", "FL");
insert into StateAgency (name, state) values ("Fish and Wildlife Conservation Commission", "FL");
insert into StateAgency (name, state) values ("Florida Courts", "FL");
insert into StateAgency (name, state) values ("Florida Geological Survey ", "FL");
insert into StateAgency (name, state) values ("Florida Legislature", "FL");
insert into StateAgency (name, state) values ("Florida Supreme Court", "FL");
insert into StateAgency (name, state) values ("Office of Program Policy Analysis and Government Accountability", "FL");
insert into StateAgency (name, state) values ("Prison Rehabilitative Industries & Diversified Enterprises Inc", "FL");
insert into StateAgency (name, state) values ("Public Service Commission", "FL");
insert into StateAgency (name, state) values ("State Board of Administration", "FL");